apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: i31uowwlx-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/i31uowwlx-java-quarkus-gitops